package dao;

import bean.caigouxinxiBean;
import bean.caigouxinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class caigouxinxiBeanDAOImpl extends SqlMapClientDaoSupport implements caigouxinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public caigouxinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(caigouxinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("caigouxinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(caigouxinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("caigouxinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        caigouxinxiBean key = new caigouxinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("caigouxinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(caigouxinxiBean record) {
        getSqlMapClientTemplate().insert("caigouxinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(caigouxinxiBean record) {
        getSqlMapClientTemplate().insert("caigouxinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<caigouxinxiBean> selectByExample(caigouxinxiBeanExample example) {
        List<caigouxinxiBean> list = getSqlMapClientTemplate().queryForList("caigouxinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public caigouxinxiBean selectByPrimaryKey(Integer id) {
        caigouxinxiBean key = new caigouxinxiBean();
        key.setId(id);
        caigouxinxiBean record = (caigouxinxiBean) getSqlMapClientTemplate().queryForObject("caigouxinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(caigouxinxiBean record, caigouxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("caigouxinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(caigouxinxiBean record, caigouxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("caigouxinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(caigouxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("caigouxinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(caigouxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("caigouxinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends caigouxinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, caigouxinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}