package dao;

import bean.chengyunshangxinxiBean;
import bean.chengyunshangxinxiBeanExample;
import java.util.List;

public interface chengyunshangxinxiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(chengyunshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(chengyunshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(chengyunshangxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(chengyunshangxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<chengyunshangxinxiBean> selectByExample(chengyunshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    chengyunshangxinxiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(chengyunshangxinxiBean record, chengyunshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(chengyunshangxinxiBean record, chengyunshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(chengyunshangxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(chengyunshangxinxiBean record);
}