package dao;

import bean.chengyunshangxinxiBean;
import bean.chengyunshangxinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class chengyunshangxinxiBeanDAOImpl extends SqlMapClientDaoSupport implements chengyunshangxinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public chengyunshangxinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(chengyunshangxinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("chengyunshangxinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(chengyunshangxinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("chengyunshangxinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        chengyunshangxinxiBean key = new chengyunshangxinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("chengyunshangxinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(chengyunshangxinxiBean record) {
        getSqlMapClientTemplate().insert("chengyunshangxinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(chengyunshangxinxiBean record) {
        getSqlMapClientTemplate().insert("chengyunshangxinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<chengyunshangxinxiBean> selectByExample(chengyunshangxinxiBeanExample example) {
        List<chengyunshangxinxiBean> list = getSqlMapClientTemplate().queryForList("chengyunshangxinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public chengyunshangxinxiBean selectByPrimaryKey(Integer id) {
        chengyunshangxinxiBean key = new chengyunshangxinxiBean();
        key.setId(id);
        chengyunshangxinxiBean record = (chengyunshangxinxiBean) getSqlMapClientTemplate().queryForObject("chengyunshangxinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(chengyunshangxinxiBean record, chengyunshangxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("chengyunshangxinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(chengyunshangxinxiBean record, chengyunshangxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("chengyunshangxinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(chengyunshangxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("chengyunshangxinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(chengyunshangxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("chengyunshangxinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table chengyunshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends chengyunshangxinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, chengyunshangxinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}