package dao;

import bean.gongyingshangxinxiBean;
import bean.gongyingshangxinxiBeanExample;
import java.util.List;

public interface gongyingshangxinxiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(gongyingshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(gongyingshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(gongyingshangxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(gongyingshangxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<gongyingshangxinxiBean> selectByExample(gongyingshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    gongyingshangxinxiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(gongyingshangxinxiBean record, gongyingshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(gongyingshangxinxiBean record, gongyingshangxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(gongyingshangxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(gongyingshangxinxiBean record);
}