package dao;

import bean.gongyingshangxinxiBean;
import bean.gongyingshangxinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class gongyingshangxinxiBeanDAOImpl extends SqlMapClientDaoSupport implements gongyingshangxinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public gongyingshangxinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(gongyingshangxinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("gongyingshangxinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(gongyingshangxinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("gongyingshangxinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        gongyingshangxinxiBean key = new gongyingshangxinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("gongyingshangxinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(gongyingshangxinxiBean record) {
        getSqlMapClientTemplate().insert("gongyingshangxinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(gongyingshangxinxiBean record) {
        getSqlMapClientTemplate().insert("gongyingshangxinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<gongyingshangxinxiBean> selectByExample(gongyingshangxinxiBeanExample example) {
        List<gongyingshangxinxiBean> list = getSqlMapClientTemplate().queryForList("gongyingshangxinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public gongyingshangxinxiBean selectByPrimaryKey(Integer id) {
        gongyingshangxinxiBean key = new gongyingshangxinxiBean();
        key.setId(id);
        gongyingshangxinxiBean record = (gongyingshangxinxiBean) getSqlMapClientTemplate().queryForObject("gongyingshangxinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(gongyingshangxinxiBean record, gongyingshangxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("gongyingshangxinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(gongyingshangxinxiBean record, gongyingshangxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("gongyingshangxinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(gongyingshangxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("gongyingshangxinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(gongyingshangxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("gongyingshangxinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table gongyingshangxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends gongyingshangxinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, gongyingshangxinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}