package dao;

import bean.huiyuanjifenBean;
import bean.huiyuanjifenBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class huiyuanjifenBeanDAOImpl extends SqlMapClientDaoSupport implements huiyuanjifenBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public huiyuanjifenBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(huiyuanjifenBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("huiyuanjifen.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(huiyuanjifenBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("huiyuanjifen.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        huiyuanjifenBean key = new huiyuanjifenBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("huiyuanjifen.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(huiyuanjifenBean record) {
        getSqlMapClientTemplate().insert("huiyuanjifen.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(huiyuanjifenBean record) {
        getSqlMapClientTemplate().insert("huiyuanjifen.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<huiyuanjifenBean> selectByExample(huiyuanjifenBeanExample example) {
        List<huiyuanjifenBean> list = getSqlMapClientTemplate().queryForList("huiyuanjifen.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public huiyuanjifenBean selectByPrimaryKey(Integer id) {
        huiyuanjifenBean key = new huiyuanjifenBean();
        key.setId(id);
        huiyuanjifenBean record = (huiyuanjifenBean) getSqlMapClientTemplate().queryForObject("huiyuanjifen.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(huiyuanjifenBean record, huiyuanjifenBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("huiyuanjifen.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(huiyuanjifenBean record, huiyuanjifenBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("huiyuanjifen.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(huiyuanjifenBean record) {
        int rows = getSqlMapClientTemplate().update("huiyuanjifen.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(huiyuanjifenBean record) {
        int rows = getSqlMapClientTemplate().update("huiyuanjifen.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends huiyuanjifenBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, huiyuanjifenBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}