package dao;

import bean.huiyuanxinxiBean;
import bean.huiyuanxinxiBeanExample;
import java.util.List;

public interface huiyuanxinxiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(huiyuanxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(huiyuanxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(huiyuanxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(huiyuanxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<huiyuanxinxiBean> selectByExample(huiyuanxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    huiyuanxinxiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(huiyuanxinxiBean record, huiyuanxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(huiyuanxinxiBean record, huiyuanxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(huiyuanxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table huiyuanxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(huiyuanxinxiBean record);
}