package dao;

import bean.jiageshezhiBean;
import bean.jiageshezhiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class jiageshezhiBeanDAOImpl extends SqlMapClientDaoSupport implements jiageshezhiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public jiageshezhiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(jiageshezhiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("jiageshezhi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(jiageshezhiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("jiageshezhi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        jiageshezhiBean key = new jiageshezhiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("jiageshezhi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(jiageshezhiBean record) {
        getSqlMapClientTemplate().insert("jiageshezhi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(jiageshezhiBean record) {
        getSqlMapClientTemplate().insert("jiageshezhi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<jiageshezhiBean> selectByExample(jiageshezhiBeanExample example) {
        List<jiageshezhiBean> list = getSqlMapClientTemplate().queryForList("jiageshezhi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public jiageshezhiBean selectByPrimaryKey(Integer id) {
        jiageshezhiBean key = new jiageshezhiBean();
        key.setId(id);
        jiageshezhiBean record = (jiageshezhiBean) getSqlMapClientTemplate().queryForObject("jiageshezhi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(jiageshezhiBean record, jiageshezhiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("jiageshezhi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(jiageshezhiBean record, jiageshezhiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("jiageshezhi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(jiageshezhiBean record) {
        int rows = getSqlMapClientTemplate().update("jiageshezhi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(jiageshezhiBean record) {
        int rows = getSqlMapClientTemplate().update("jiageshezhi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table jiageshezhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends jiageshezhiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, jiageshezhiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}