package dao;

import bean.neibuyuangongguanliBean;
import bean.neibuyuangongguanliBeanExample;
import java.util.List;

public interface neibuyuangongguanliBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(neibuyuangongguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(neibuyuangongguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(neibuyuangongguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(neibuyuangongguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<neibuyuangongguanliBean> selectByExample(neibuyuangongguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    neibuyuangongguanliBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(neibuyuangongguanliBean record, neibuyuangongguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(neibuyuangongguanliBean record, neibuyuangongguanliBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(neibuyuangongguanliBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(neibuyuangongguanliBean record);
}