package dao;

import bean.neibuyuangongguanliBean;
import bean.neibuyuangongguanliBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class neibuyuangongguanliBeanDAOImpl extends SqlMapClientDaoSupport implements neibuyuangongguanliBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public neibuyuangongguanliBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(neibuyuangongguanliBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("neibuyuangongguanli.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(neibuyuangongguanliBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("neibuyuangongguanli.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        neibuyuangongguanliBean key = new neibuyuangongguanliBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("neibuyuangongguanli.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(neibuyuangongguanliBean record) {
        getSqlMapClientTemplate().insert("neibuyuangongguanli.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(neibuyuangongguanliBean record) {
        getSqlMapClientTemplate().insert("neibuyuangongguanli.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<neibuyuangongguanliBean> selectByExample(neibuyuangongguanliBeanExample example) {
        List<neibuyuangongguanliBean> list = getSqlMapClientTemplate().queryForList("neibuyuangongguanli.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public neibuyuangongguanliBean selectByPrimaryKey(Integer id) {
        neibuyuangongguanliBean key = new neibuyuangongguanliBean();
        key.setId(id);
        neibuyuangongguanliBean record = (neibuyuangongguanliBean) getSqlMapClientTemplate().queryForObject("neibuyuangongguanli.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(neibuyuangongguanliBean record, neibuyuangongguanliBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("neibuyuangongguanli.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(neibuyuangongguanliBean record, neibuyuangongguanliBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("neibuyuangongguanli.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(neibuyuangongguanliBean record) {
        int rows = getSqlMapClientTemplate().update("neibuyuangongguanli.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(neibuyuangongguanliBean record) {
        int rows = getSqlMapClientTemplate().update("neibuyuangongguanli.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends neibuyuangongguanliBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, neibuyuangongguanliBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}