package dao;

import bean.shangpinleixingBean;
import bean.shangpinleixingBeanExample;
import java.util.List;

public interface shangpinleixingBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(shangpinleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(shangpinleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(shangpinleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(shangpinleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<shangpinleixingBean> selectByExample(shangpinleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    shangpinleixingBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(shangpinleixingBean record, shangpinleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(shangpinleixingBean record, shangpinleixingBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(shangpinleixingBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(shangpinleixingBean record);
}