package dao;

import bean.shangpinleixingBean;
import bean.shangpinleixingBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class shangpinleixingBeanDAOImpl extends SqlMapClientDaoSupport implements shangpinleixingBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public shangpinleixingBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(shangpinleixingBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("shangpinleixing.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(shangpinleixingBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("shangpinleixing.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        shangpinleixingBean key = new shangpinleixingBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("shangpinleixing.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(shangpinleixingBean record) {
        getSqlMapClientTemplate().insert("shangpinleixing.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(shangpinleixingBean record) {
        getSqlMapClientTemplate().insert("shangpinleixing.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<shangpinleixingBean> selectByExample(shangpinleixingBeanExample example) {
        List<shangpinleixingBean> list = getSqlMapClientTemplate().queryForList("shangpinleixing.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public shangpinleixingBean selectByPrimaryKey(Integer id) {
        shangpinleixingBean key = new shangpinleixingBean();
        key.setId(id);
        shangpinleixingBean record = (shangpinleixingBean) getSqlMapClientTemplate().queryForObject("shangpinleixing.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(shangpinleixingBean record, shangpinleixingBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shangpinleixing.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(shangpinleixingBean record, shangpinleixingBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shangpinleixing.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(shangpinleixingBean record) {
        int rows = getSqlMapClientTemplate().update("shangpinleixing.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(shangpinleixingBean record) {
        int rows = getSqlMapClientTemplate().update("shangpinleixing.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends shangpinleixingBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, shangpinleixingBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}