package dao;

import bean.shouyehuandengpianBean;
import bean.shouyehuandengpianBeanExample;
import java.util.List;

public interface shouyehuandengpianBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(shouyehuandengpianBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(shouyehuandengpianBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(shouyehuandengpianBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(shouyehuandengpianBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<shouyehuandengpianBean> selectByExample(shouyehuandengpianBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    shouyehuandengpianBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(shouyehuandengpianBean record, shouyehuandengpianBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(shouyehuandengpianBean record, shouyehuandengpianBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(shouyehuandengpianBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table shouyehuandengpian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(shouyehuandengpianBean record);
}