package dao;

import bean.user_info_detailBean;
import bean.user_info_detailBeanExample;
import java.util.List;

public interface user_info_detailBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(user_info_detailBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(user_info_detailBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(user_info_detailBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(user_info_detailBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<user_info_detailBean> selectByExample(user_info_detailBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    user_info_detailBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(user_info_detailBean record, user_info_detailBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(user_info_detailBean record, user_info_detailBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(user_info_detailBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_info_detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(user_info_detailBean record);
}