package dao;

import bean.xiaoshouxinxiBean;
import bean.xiaoshouxinxiBeanExample;
import java.util.List;

public interface xiaoshouxinxiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(xiaoshouxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(xiaoshouxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(xiaoshouxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(xiaoshouxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<xiaoshouxinxiBean> selectByExample(xiaoshouxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    xiaoshouxinxiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(xiaoshouxinxiBean record, xiaoshouxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(xiaoshouxinxiBean record, xiaoshouxinxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(xiaoshouxinxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(xiaoshouxinxiBean record);
}