package dao;

import bean.xiaoshouxinxi_mingxiBean;
import bean.xiaoshouxinxi_mingxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class xiaoshouxinxi_mingxiBeanDAOImpl extends SqlMapClientDaoSupport implements xiaoshouxinxi_mingxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public xiaoshouxinxi_mingxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(xiaoshouxinxi_mingxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("xiaoshouxinxi_mingxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(xiaoshouxinxi_mingxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("xiaoshouxinxi_mingxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        xiaoshouxinxi_mingxiBean key = new xiaoshouxinxi_mingxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("xiaoshouxinxi_mingxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(xiaoshouxinxi_mingxiBean record) {
        getSqlMapClientTemplate().insert("xiaoshouxinxi_mingxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(xiaoshouxinxi_mingxiBean record) {
        getSqlMapClientTemplate().insert("xiaoshouxinxi_mingxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<xiaoshouxinxi_mingxiBean> selectByExample(xiaoshouxinxi_mingxiBeanExample example) {
        List<xiaoshouxinxi_mingxiBean> list = getSqlMapClientTemplate().queryForList("xiaoshouxinxi_mingxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public xiaoshouxinxi_mingxiBean selectByPrimaryKey(Integer id) {
        xiaoshouxinxi_mingxiBean key = new xiaoshouxinxi_mingxiBean();
        key.setId(id);
        xiaoshouxinxi_mingxiBean record = (xiaoshouxinxi_mingxiBean) getSqlMapClientTemplate().queryForObject("xiaoshouxinxi_mingxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(xiaoshouxinxi_mingxiBean record, xiaoshouxinxi_mingxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi_mingxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(xiaoshouxinxi_mingxiBean record, xiaoshouxinxi_mingxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi_mingxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(xiaoshouxinxi_mingxiBean record) {
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi_mingxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(xiaoshouxinxi_mingxiBean record) {
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi_mingxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends xiaoshouxinxi_mingxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, xiaoshouxinxi_mingxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}