package dao;

import bean.xiaoshouxinxiBean;
import bean.xiaoshouxinxiBeanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class xiaoshouxinxiBeanDAOImpl extends SqlMapClientDaoSupport implements xiaoshouxinxiBeanDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public xiaoshouxinxiBeanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int countByExample(xiaoshouxinxiBeanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("xiaoshouxinxi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByExample(xiaoshouxinxiBeanExample example) {
        int rows = getSqlMapClientTemplate().delete("xiaoshouxinxi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        xiaoshouxinxiBean key = new xiaoshouxinxiBean();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("xiaoshouxinxi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insert(xiaoshouxinxiBean record) {
        getSqlMapClientTemplate().insert("xiaoshouxinxi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void insertSelective(xiaoshouxinxiBean record) {
        getSqlMapClientTemplate().insert("xiaoshouxinxi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    @SuppressWarnings("unchecked")
    public List<xiaoshouxinxiBean> selectByExample(xiaoshouxinxiBeanExample example) {
        List<xiaoshouxinxiBean> list = getSqlMapClientTemplate().queryForList("xiaoshouxinxi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public xiaoshouxinxiBean selectByPrimaryKey(Integer id) {
        xiaoshouxinxiBean key = new xiaoshouxinxiBean();
        key.setId(id);
        xiaoshouxinxiBean record = (xiaoshouxinxiBean) getSqlMapClientTemplate().queryForObject("xiaoshouxinxi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExampleSelective(xiaoshouxinxiBean record, xiaoshouxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByExample(xiaoshouxinxiBean record, xiaoshouxinxiBeanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKeySelective(xiaoshouxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public int updateByPrimaryKey(xiaoshouxinxiBean record) {
        int rows = getSqlMapClientTemplate().update("xiaoshouxinxi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table xiaoshouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private static class UpdateByExampleParms extends xiaoshouxinxiBeanExample {
        private Object record;

        public UpdateByExampleParms(Object record, xiaoshouxinxiBeanExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}