package dao;

import bean.xiaoshouxinxi_mingxiBean;
import bean.xiaoshouxinxi_mingxiBeanExample;
import java.util.List;

public interface xiaoshouxinxi_mingxiBeanDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int countByExample(xiaoshouxinxi_mingxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByExample(xiaoshouxinxi_mingxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insert(xiaoshouxinxi_mingxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    void insertSelective(xiaoshouxinxi_mingxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    List<xiaoshouxinxi_mingxiBean> selectByExample(xiaoshouxinxi_mingxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    xiaoshouxinxi_mingxiBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExampleSelective(xiaoshouxinxi_mingxiBean record, xiaoshouxinxi_mingxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByExample(xiaoshouxinxi_mingxiBean record, xiaoshouxinxi_mingxiBeanExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKeySelective(xiaoshouxinxi_mingxiBean record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    int updateByPrimaryKey(xiaoshouxinxi_mingxiBean record);
}