package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class caigouxinxiBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public caigouxinxiBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected caigouxinxiBeanExample(caigouxinxiBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table caigouxinxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andShangpinmingchengIsNull() {
            addCriterion("shangpinmingcheng is null");
            return this;
        }

        public Criteria andShangpinmingchengIsNotNull() {
            addCriterion("shangpinmingcheng is not null");
            return this;
        }

        public Criteria andShangpinmingchengEqualTo(String value) {
            addCriterion("shangpinmingcheng =", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengNotEqualTo(String value) {
            addCriterion("shangpinmingcheng <>", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengGreaterThan(String value) {
            addCriterion("shangpinmingcheng >", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengGreaterThanOrEqualTo(String value) {
            addCriterion("shangpinmingcheng >=", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengLessThan(String value) {
            addCriterion("shangpinmingcheng <", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengLessThanOrEqualTo(String value) {
            addCriterion("shangpinmingcheng <=", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengLike(String value) {
            addCriterion("shangpinmingcheng like", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengNotLike(String value) {
            addCriterion("shangpinmingcheng not like", value, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengIn(List<String> values) {
            addCriterion("shangpinmingcheng in", values, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengNotIn(List<String> values) {
            addCriterion("shangpinmingcheng not in", values, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengBetween(String value1, String value2) {
            addCriterion("shangpinmingcheng between", value1, value2, "shangpinmingcheng");
            return this;
        }

        public Criteria andShangpinmingchengNotBetween(String value1, String value2) {
            addCriterion("shangpinmingcheng not between", value1, value2, "shangpinmingcheng");
            return this;
        }

        public Criteria andHuohaoIsNull() {
            addCriterion("huohao is null");
            return this;
        }

        public Criteria andHuohaoIsNotNull() {
            addCriterion("huohao is not null");
            return this;
        }

        public Criteria andHuohaoEqualTo(String value) {
            addCriterion("huohao =", value, "huohao");
            return this;
        }

        public Criteria andHuohaoNotEqualTo(String value) {
            addCriterion("huohao <>", value, "huohao");
            return this;
        }

        public Criteria andHuohaoGreaterThan(String value) {
            addCriterion("huohao >", value, "huohao");
            return this;
        }

        public Criteria andHuohaoGreaterThanOrEqualTo(String value) {
            addCriterion("huohao >=", value, "huohao");
            return this;
        }

        public Criteria andHuohaoLessThan(String value) {
            addCriterion("huohao <", value, "huohao");
            return this;
        }

        public Criteria andHuohaoLessThanOrEqualTo(String value) {
            addCriterion("huohao <=", value, "huohao");
            return this;
        }

        public Criteria andHuohaoLike(String value) {
            addCriterion("huohao like", value, "huohao");
            return this;
        }

        public Criteria andHuohaoNotLike(String value) {
            addCriterion("huohao not like", value, "huohao");
            return this;
        }

        public Criteria andHuohaoIn(List<String> values) {
            addCriterion("huohao in", values, "huohao");
            return this;
        }

        public Criteria andHuohaoNotIn(List<String> values) {
            addCriterion("huohao not in", values, "huohao");
            return this;
        }

        public Criteria andHuohaoBetween(String value1, String value2) {
            addCriterion("huohao between", value1, value2, "huohao");
            return this;
        }

        public Criteria andHuohaoNotBetween(String value1, String value2) {
            addCriterion("huohao not between", value1, value2, "huohao");
            return this;
        }

        public Criteria andShangpinleixingIsNull() {
            addCriterion("shangpinleixing is null");
            return this;
        }

        public Criteria andShangpinleixingIsNotNull() {
            addCriterion("shangpinleixing is not null");
            return this;
        }

        public Criteria andShangpinleixingEqualTo(String value) {
            addCriterion("shangpinleixing =", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingNotEqualTo(String value) {
            addCriterion("shangpinleixing <>", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingGreaterThan(String value) {
            addCriterion("shangpinleixing >", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingGreaterThanOrEqualTo(String value) {
            addCriterion("shangpinleixing >=", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingLessThan(String value) {
            addCriterion("shangpinleixing <", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingLessThanOrEqualTo(String value) {
            addCriterion("shangpinleixing <=", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingLike(String value) {
            addCriterion("shangpinleixing like", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingNotLike(String value) {
            addCriterion("shangpinleixing not like", value, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingIn(List<String> values) {
            addCriterion("shangpinleixing in", values, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingNotIn(List<String> values) {
            addCriterion("shangpinleixing not in", values, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingBetween(String value1, String value2) {
            addCriterion("shangpinleixing between", value1, value2, "shangpinleixing");
            return this;
        }

        public Criteria andShangpinleixingNotBetween(String value1, String value2) {
            addCriterion("shangpinleixing not between", value1, value2, "shangpinleixing");
            return this;
        }

        public Criteria andGongyingshangIsNull() {
            addCriterion("gongyingshang is null");
            return this;
        }

        public Criteria andGongyingshangIsNotNull() {
            addCriterion("gongyingshang is not null");
            return this;
        }

        public Criteria andGongyingshangEqualTo(String value) {
            addCriterion("gongyingshang =", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangNotEqualTo(String value) {
            addCriterion("gongyingshang <>", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangGreaterThan(String value) {
            addCriterion("gongyingshang >", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangGreaterThanOrEqualTo(String value) {
            addCriterion("gongyingshang >=", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangLessThan(String value) {
            addCriterion("gongyingshang <", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangLessThanOrEqualTo(String value) {
            addCriterion("gongyingshang <=", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangLike(String value) {
            addCriterion("gongyingshang like", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangNotLike(String value) {
            addCriterion("gongyingshang not like", value, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangIn(List<String> values) {
            addCriterion("gongyingshang in", values, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangNotIn(List<String> values) {
            addCriterion("gongyingshang not in", values, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangBetween(String value1, String value2) {
            addCriterion("gongyingshang between", value1, value2, "gongyingshang");
            return this;
        }

        public Criteria andGongyingshangNotBetween(String value1, String value2) {
            addCriterion("gongyingshang not between", value1, value2, "gongyingshang");
            return this;
        }

        public Criteria andChengyunshangIsNull() {
            addCriterion("chengyunshang is null");
            return this;
        }

        public Criteria andChengyunshangIsNotNull() {
            addCriterion("chengyunshang is not null");
            return this;
        }

        public Criteria andChengyunshangEqualTo(String value) {
            addCriterion("chengyunshang =", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangNotEqualTo(String value) {
            addCriterion("chengyunshang <>", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangGreaterThan(String value) {
            addCriterion("chengyunshang >", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangGreaterThanOrEqualTo(String value) {
            addCriterion("chengyunshang >=", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangLessThan(String value) {
            addCriterion("chengyunshang <", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangLessThanOrEqualTo(String value) {
            addCriterion("chengyunshang <=", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangLike(String value) {
            addCriterion("chengyunshang like", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangNotLike(String value) {
            addCriterion("chengyunshang not like", value, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangIn(List<String> values) {
            addCriterion("chengyunshang in", values, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangNotIn(List<String> values) {
            addCriterion("chengyunshang not in", values, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangBetween(String value1, String value2) {
            addCriterion("chengyunshang between", value1, value2, "chengyunshang");
            return this;
        }

        public Criteria andChengyunshangNotBetween(String value1, String value2) {
            addCriterion("chengyunshang not between", value1, value2, "chengyunshang");
            return this;
        }

        public Criteria andDanjiaIsNull() {
            addCriterion("danjia is null");
            return this;
        }

        public Criteria andDanjiaIsNotNull() {
            addCriterion("danjia is not null");
            return this;
        }

        public Criteria andDanjiaEqualTo(String value) {
            addCriterion("danjia =", value, "danjia");
            return this;
        }

        public Criteria andDanjiaNotEqualTo(String value) {
            addCriterion("danjia <>", value, "danjia");
            return this;
        }

        public Criteria andDanjiaGreaterThan(String value) {
            addCriterion("danjia >", value, "danjia");
            return this;
        }

        public Criteria andDanjiaGreaterThanOrEqualTo(String value) {
            addCriterion("danjia >=", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLessThan(String value) {
            addCriterion("danjia <", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLessThanOrEqualTo(String value) {
            addCriterion("danjia <=", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLike(String value) {
            addCriterion("danjia like", value, "danjia");
            return this;
        }

        public Criteria andDanjiaNotLike(String value) {
            addCriterion("danjia not like", value, "danjia");
            return this;
        }

        public Criteria andDanjiaIn(List<String> values) {
            addCriterion("danjia in", values, "danjia");
            return this;
        }

        public Criteria andDanjiaNotIn(List<String> values) {
            addCriterion("danjia not in", values, "danjia");
            return this;
        }

        public Criteria andDanjiaBetween(String value1, String value2) {
            addCriterion("danjia between", value1, value2, "danjia");
            return this;
        }

        public Criteria andDanjiaNotBetween(String value1, String value2) {
            addCriterion("danjia not between", value1, value2, "danjia");
            return this;
        }

        public Criteria andCaigouriqiIsNull() {
            addCriterion("caigouriqi is null");
            return this;
        }

        public Criteria andCaigouriqiIsNotNull() {
            addCriterion("caigouriqi is not null");
            return this;
        }

        public Criteria andCaigouriqiEqualTo(String value) {
            addCriterion("caigouriqi =", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiNotEqualTo(String value) {
            addCriterion("caigouriqi <>", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiGreaterThan(String value) {
            addCriterion("caigouriqi >", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiGreaterThanOrEqualTo(String value) {
            addCriterion("caigouriqi >=", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiLessThan(String value) {
            addCriterion("caigouriqi <", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiLessThanOrEqualTo(String value) {
            addCriterion("caigouriqi <=", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiLike(String value) {
            addCriterion("caigouriqi like", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiNotLike(String value) {
            addCriterion("caigouriqi not like", value, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiIn(List<String> values) {
            addCriterion("caigouriqi in", values, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiNotIn(List<String> values) {
            addCriterion("caigouriqi not in", values, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiBetween(String value1, String value2) {
            addCriterion("caigouriqi between", value1, value2, "caigouriqi");
            return this;
        }

        public Criteria andCaigouriqiNotBetween(String value1, String value2) {
            addCriterion("caigouriqi not between", value1, value2, "caigouriqi");
            return this;
        }

        public Criteria andCaigourenIsNull() {
            addCriterion("caigouren is null");
            return this;
        }

        public Criteria andCaigourenIsNotNull() {
            addCriterion("caigouren is not null");
            return this;
        }

        public Criteria andCaigourenEqualTo(String value) {
            addCriterion("caigouren =", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenNotEqualTo(String value) {
            addCriterion("caigouren <>", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenGreaterThan(String value) {
            addCriterion("caigouren >", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenGreaterThanOrEqualTo(String value) {
            addCriterion("caigouren >=", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenLessThan(String value) {
            addCriterion("caigouren <", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenLessThanOrEqualTo(String value) {
            addCriterion("caigouren <=", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenLike(String value) {
            addCriterion("caigouren like", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenNotLike(String value) {
            addCriterion("caigouren not like", value, "caigouren");
            return this;
        }

        public Criteria andCaigourenIn(List<String> values) {
            addCriterion("caigouren in", values, "caigouren");
            return this;
        }

        public Criteria andCaigourenNotIn(List<String> values) {
            addCriterion("caigouren not in", values, "caigouren");
            return this;
        }

        public Criteria andCaigourenBetween(String value1, String value2) {
            addCriterion("caigouren between", value1, value2, "caigouren");
            return this;
        }

        public Criteria andCaigourenNotBetween(String value1, String value2) {
            addCriterion("caigouren not between", value1, value2, "caigouren");
            return this;
        }

        public Criteria andShuliangIsNull() {
            addCriterion("shuliang is null");
            return this;
        }

        public Criteria andShuliangIsNotNull() {
            addCriterion("shuliang is not null");
            return this;
        }

        public Criteria andShuliangEqualTo(String value) {
            addCriterion("shuliang =", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotEqualTo(String value) {
            addCriterion("shuliang <>", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThan(String value) {
            addCriterion("shuliang >", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThanOrEqualTo(String value) {
            addCriterion("shuliang >=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThan(String value) {
            addCriterion("shuliang <", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThanOrEqualTo(String value) {
            addCriterion("shuliang <=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLike(String value) {
            addCriterion("shuliang like", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotLike(String value) {
            addCriterion("shuliang not like", value, "shuliang");
            return this;
        }

        public Criteria andShuliangIn(List<String> values) {
            addCriterion("shuliang in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangNotIn(List<String> values) {
            addCriterion("shuliang not in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangBetween(String value1, String value2) {
            addCriterion("shuliang between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andShuliangNotBetween(String value1, String value2) {
            addCriterion("shuliang not between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andKucunliangIsNull() {
            addCriterion("kucunliang is null");
            return this;
        }

        public Criteria andKucunliangIsNotNull() {
            addCriterion("kucunliang is not null");
            return this;
        }

        public Criteria andKucunliangEqualTo(String value) {
            addCriterion("kucunliang =", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangNotEqualTo(String value) {
            addCriterion("kucunliang <>", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangGreaterThan(String value) {
            addCriterion("kucunliang >", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangGreaterThanOrEqualTo(String value) {
            addCriterion("kucunliang >=", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangLessThan(String value) {
            addCriterion("kucunliang <", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangLessThanOrEqualTo(String value) {
            addCriterion("kucunliang <=", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangLike(String value) {
            addCriterion("kucunliang like", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangNotLike(String value) {
            addCriterion("kucunliang not like", value, "kucunliang");
            return this;
        }

        public Criteria andKucunliangIn(List<String> values) {
            addCriterion("kucunliang in", values, "kucunliang");
            return this;
        }

        public Criteria andKucunliangNotIn(List<String> values) {
            addCriterion("kucunliang not in", values, "kucunliang");
            return this;
        }

        public Criteria andKucunliangBetween(String value1, String value2) {
            addCriterion("kucunliang between", value1, value2, "kucunliang");
            return this;
        }

        public Criteria andKucunliangNotBetween(String value1, String value2) {
            addCriterion("kucunliang not between", value1, value2, "kucunliang");
            return this;
        }

        public Criteria andZhuangtaiIsNull() {
            addCriterion("zhuangtai is null");
            return this;
        }

        public Criteria andZhuangtaiIsNotNull() {
            addCriterion("zhuangtai is not null");
            return this;
        }

        public Criteria andZhuangtaiEqualTo(String value) {
            addCriterion("zhuangtai =", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiNotEqualTo(String value) {
            addCriterion("zhuangtai <>", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiGreaterThan(String value) {
            addCriterion("zhuangtai >", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiGreaterThanOrEqualTo(String value) {
            addCriterion("zhuangtai >=", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiLessThan(String value) {
            addCriterion("zhuangtai <", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiLessThanOrEqualTo(String value) {
            addCriterion("zhuangtai <=", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiLike(String value) {
            addCriterion("zhuangtai like", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiNotLike(String value) {
            addCriterion("zhuangtai not like", value, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiIn(List<String> values) {
            addCriterion("zhuangtai in", values, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiNotIn(List<String> values) {
            addCriterion("zhuangtai not in", values, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiBetween(String value1, String value2) {
            addCriterion("zhuangtai between", value1, value2, "zhuangtai");
            return this;
        }

        public Criteria andZhuangtaiNotBetween(String value1, String value2) {
            addCriterion("zhuangtai not between", value1, value2, "zhuangtai");
            return this;
        }

        public Criteria andFujianIsNull() {
            addCriterion("fuJian is null");
            return this;
        }

        public Criteria andFujianIsNotNull() {
            addCriterion("fuJian is not null");
            return this;
        }

        public Criteria andFujianEqualTo(String value) {
            addCriterion("fuJian =", value, "fujian");
            return this;
        }

        public Criteria andFujianNotEqualTo(String value) {
            addCriterion("fuJian <>", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThan(String value) {
            addCriterion("fuJian >", value, "fujian");
            return this;
        }

        public Criteria andFujianGreaterThanOrEqualTo(String value) {
            addCriterion("fuJian >=", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThan(String value) {
            addCriterion("fuJian <", value, "fujian");
            return this;
        }

        public Criteria andFujianLessThanOrEqualTo(String value) {
            addCriterion("fuJian <=", value, "fujian");
            return this;
        }

        public Criteria andFujianLike(String value) {
            addCriterion("fuJian like", value, "fujian");
            return this;
        }

        public Criteria andFujianNotLike(String value) {
            addCriterion("fuJian not like", value, "fujian");
            return this;
        }

        public Criteria andFujianIn(List<String> values) {
            addCriterion("fuJian in", values, "fujian");
            return this;
        }

        public Criteria andFujianNotIn(List<String> values) {
            addCriterion("fuJian not in", values, "fujian");
            return this;
        }

        public Criteria andFujianBetween(String value1, String value2) {
            addCriterion("fuJian between", value1, value2, "fujian");
            return this;
        }

        public Criteria andFujianNotBetween(String value1, String value2) {
            addCriterion("fuJian not between", value1, value2, "fujian");
            return this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorId is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorId is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("operatorId =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("operatorId <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("operatorId >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("operatorId >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("operatorId <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("operatorId <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("operatorId like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("operatorId not like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("operatorId in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("operatorId not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("operatorId between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("operatorId not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andItimeIsNull() {
            addCriterion("itime is null");
            return this;
        }

        public Criteria andItimeIsNotNull() {
            addCriterion("itime is not null");
            return this;
        }

        public Criteria andItimeEqualTo(String value) {
            addCriterion("itime =", value, "itime");
            return this;
        }

        public Criteria andItimeNotEqualTo(String value) {
            addCriterion("itime <>", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThan(String value) {
            addCriterion("itime >", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThanOrEqualTo(String value) {
            addCriterion("itime >=", value, "itime");
            return this;
        }

        public Criteria andItimeLessThan(String value) {
            addCriterion("itime <", value, "itime");
            return this;
        }

        public Criteria andItimeLessThanOrEqualTo(String value) {
            addCriterion("itime <=", value, "itime");
            return this;
        }

        public Criteria andItimeLike(String value) {
            addCriterion("itime like", value, "itime");
            return this;
        }

        public Criteria andItimeNotLike(String value) {
            addCriterion("itime not like", value, "itime");
            return this;
        }

        public Criteria andItimeIn(List<String> values) {
            addCriterion("itime in", values, "itime");
            return this;
        }

        public Criteria andItimeNotIn(List<String> values) {
            addCriterion("itime not in", values, "itime");
            return this;
        }

        public Criteria andItimeBetween(String value1, String value2) {
            addCriterion("itime between", value1, value2, "itime");
            return this;
        }

        public Criteria andItimeNotBetween(String value1, String value2) {
            addCriterion("itime not between", value1, value2, "itime");
            return this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteFlag is null");
            return this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteFlag is not null");
            return this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("deleteFlag =", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("deleteFlag <>", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("deleteFlag >", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag >=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("deleteFlag <", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag <=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("deleteFlag in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("deleteFlag not in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag not between", value1, value2, "deleteflag");
            return this;
        }
    }
}