package bean;

public class caigouxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.shangpinmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String shangpinmingcheng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huohao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String shangpinleixing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.gongyingshang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String gongyingshang;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.chengyunshang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String chengyunshang;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.danjia
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String danjia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.caigouriqi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String caigouriqi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.caigouren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String caigouren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.shuliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String shuliang;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.kucunliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String kucunliang;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.zhuangtai
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String zhuangtai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.fuJian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column caigouxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.id
     *
     * @return the value of caigouxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.id
     *
     * @param id the value for caigouxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.shangpinmingcheng
     *
     * @return the value of caigouxinxi.shangpinmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getShangpinmingcheng() {
        return shangpinmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.shangpinmingcheng
     *
     * @param shangpinmingcheng the value for caigouxinxi.shangpinmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setShangpinmingcheng(String shangpinmingcheng) {
        this.shangpinmingcheng = shangpinmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.huohao
     *
     * @return the value of caigouxinxi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuohao() {
        return huohao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.huohao
     *
     * @param huohao the value for caigouxinxi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuohao(String huohao) {
        this.huohao = huohao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.shangpinleixing
     *
     * @return the value of caigouxinxi.shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getShangpinleixing() {
        return shangpinleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.shangpinleixing
     *
     * @param shangpinleixing the value for caigouxinxi.shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setShangpinleixing(String shangpinleixing) {
        this.shangpinleixing = shangpinleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.gongyingshang
     *
     * @return the value of caigouxinxi.gongyingshang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getGongyingshang() {
        return gongyingshang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.gongyingshang
     *
     * @param gongyingshang the value for caigouxinxi.gongyingshang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setGongyingshang(String gongyingshang) {
        this.gongyingshang = gongyingshang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.chengyunshang
     *
     * @return the value of caigouxinxi.chengyunshang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getChengyunshang() {
        return chengyunshang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.chengyunshang
     *
     * @param chengyunshang the value for caigouxinxi.chengyunshang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setChengyunshang(String chengyunshang) {
        this.chengyunshang = chengyunshang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.danjia
     *
     * @return the value of caigouxinxi.danjia
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDanjia() {
        return danjia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.danjia
     *
     * @param danjia the value for caigouxinxi.danjia
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDanjia(String danjia) {
        this.danjia = danjia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.caigouriqi
     *
     * @return the value of caigouxinxi.caigouriqi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getCaigouriqi() {
        return caigouriqi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.caigouriqi
     *
     * @param caigouriqi the value for caigouxinxi.caigouriqi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setCaigouriqi(String caigouriqi) {
        this.caigouriqi = caigouriqi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.caigouren
     *
     * @return the value of caigouxinxi.caigouren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getCaigouren() {
        return caigouren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.caigouren
     *
     * @param caigouren the value for caigouxinxi.caigouren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setCaigouren(String caigouren) {
        this.caigouren = caigouren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.shuliang
     *
     * @return the value of caigouxinxi.shuliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.shuliang
     *
     * @param shuliang the value for caigouxinxi.shuliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setShuliang(String shuliang) {
        this.shuliang = shuliang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.kucunliang
     *
     * @return the value of caigouxinxi.kucunliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getKucunliang() {
        return kucunliang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.kucunliang
     *
     * @param kucunliang the value for caigouxinxi.kucunliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setKucunliang(String kucunliang) {
        this.kucunliang = kucunliang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.zhuangtai
     *
     * @return the value of caigouxinxi.zhuangtai
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.zhuangtai
     *
     * @param zhuangtai the value for caigouxinxi.zhuangtai
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.fuJian
     *
     * @return the value of caigouxinxi.fuJian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.fuJian
     *
     * @param fujian the value for caigouxinxi.fuJian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setFujian(String fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.operatorId
     *
     * @return the value of caigouxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.operatorId
     *
     * @param operatorid the value for caigouxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.itime
     *
     * @return the value of caigouxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.itime
     *
     * @param itime the value for caigouxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.detail
     *
     * @return the value of caigouxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.detail
     *
     * @param detail the value for caigouxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column caigouxinxi.deleteFlag
     *
     * @return the value of caigouxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column caigouxinxi.deleteFlag
     *
     * @param deleteflag the value for caigouxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}