package bean;

public class chengyunshangxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.chengyunshangmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String chengyunshangmingcheng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.chengyunleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String chengyunleixing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.chexing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String chexing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.dizhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String dizhi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.lianxiren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String lianxiren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String lianxidianhua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column chengyunshangxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.id
     *
     * @return the value of chengyunshangxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.id
     *
     * @param id the value for chengyunshangxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.chengyunshangmingcheng
     *
     * @return the value of chengyunshangxinxi.chengyunshangmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getChengyunshangmingcheng() {
        return chengyunshangmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.chengyunshangmingcheng
     *
     * @param chengyunshangmingcheng the value for chengyunshangxinxi.chengyunshangmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setChengyunshangmingcheng(String chengyunshangmingcheng) {
        this.chengyunshangmingcheng = chengyunshangmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.chengyunleixing
     *
     * @return the value of chengyunshangxinxi.chengyunleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getChengyunleixing() {
        return chengyunleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.chengyunleixing
     *
     * @param chengyunleixing the value for chengyunshangxinxi.chengyunleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setChengyunleixing(String chengyunleixing) {
        this.chengyunleixing = chengyunleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.chexing
     *
     * @return the value of chengyunshangxinxi.chexing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getChexing() {
        return chexing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.chexing
     *
     * @param chexing the value for chengyunshangxinxi.chexing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setChexing(String chexing) {
        this.chexing = chexing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.dizhi
     *
     * @return the value of chengyunshangxinxi.dizhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDizhi() {
        return dizhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.dizhi
     *
     * @param dizhi the value for chengyunshangxinxi.dizhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDizhi(String dizhi) {
        this.dizhi = dizhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.lianxiren
     *
     * @return the value of chengyunshangxinxi.lianxiren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLianxiren() {
        return lianxiren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.lianxiren
     *
     * @param lianxiren the value for chengyunshangxinxi.lianxiren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLianxiren(String lianxiren) {
        this.lianxiren = lianxiren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.lianxidianhua
     *
     * @return the value of chengyunshangxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLianxidianhua() {
        return lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.lianxidianhua
     *
     * @param lianxidianhua the value for chengyunshangxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLianxidianhua(String lianxidianhua) {
        this.lianxidianhua = lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.operatorId
     *
     * @return the value of chengyunshangxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.operatorId
     *
     * @param operatorid the value for chengyunshangxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.itime
     *
     * @return the value of chengyunshangxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.itime
     *
     * @param itime the value for chengyunshangxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.detail
     *
     * @return the value of chengyunshangxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.detail
     *
     * @param detail the value for chengyunshangxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column chengyunshangxinxi.deleteFlag
     *
     * @return the value of chengyunshangxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column chengyunshangxinxi.deleteFlag
     *
     * @param deleteflag the value for chengyunshangxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}