package bean;

public class gongyingshangxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.gongyingshangmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String gongyingshangmingcheng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.dizhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String dizhi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.lianxiren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String lianxiren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String lianxidianhua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gongyingshangxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.id
     *
     * @return the value of gongyingshangxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.id
     *
     * @param id the value for gongyingshangxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.gongyingshangmingcheng
     *
     * @return the value of gongyingshangxinxi.gongyingshangmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getGongyingshangmingcheng() {
        return gongyingshangmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.gongyingshangmingcheng
     *
     * @param gongyingshangmingcheng the value for gongyingshangxinxi.gongyingshangmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setGongyingshangmingcheng(String gongyingshangmingcheng) {
        this.gongyingshangmingcheng = gongyingshangmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.dizhi
     *
     * @return the value of gongyingshangxinxi.dizhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDizhi() {
        return dizhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.dizhi
     *
     * @param dizhi the value for gongyingshangxinxi.dizhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDizhi(String dizhi) {
        this.dizhi = dizhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.lianxiren
     *
     * @return the value of gongyingshangxinxi.lianxiren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLianxiren() {
        return lianxiren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.lianxiren
     *
     * @param lianxiren the value for gongyingshangxinxi.lianxiren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLianxiren(String lianxiren) {
        this.lianxiren = lianxiren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.lianxidianhua
     *
     * @return the value of gongyingshangxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLianxidianhua() {
        return lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.lianxidianhua
     *
     * @param lianxidianhua the value for gongyingshangxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLianxidianhua(String lianxidianhua) {
        this.lianxidianhua = lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.operatorId
     *
     * @return the value of gongyingshangxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.operatorId
     *
     * @param operatorid the value for gongyingshangxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.itime
     *
     * @return the value of gongyingshangxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.itime
     *
     * @param itime the value for gongyingshangxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.detail
     *
     * @return the value of gongyingshangxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.detail
     *
     * @param detail the value for gongyingshangxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gongyingshangxinxi.deleteFlag
     *
     * @return the value of gongyingshangxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gongyingshangxinxi.deleteFlag
     *
     * @param deleteflag the value for gongyingshangxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}