package bean;

public class huiyuanxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.huiyuanmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huiyuanmingcheng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.huiyuanbianhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huiyuanbianhao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String lianxidianhua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.fuJian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String fujian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanxinxi.zhuangtai
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String zhuangtai;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.id
     *
     * @return the value of huiyuanxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.id
     *
     * @param id the value for huiyuanxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.huiyuanmingcheng
     *
     * @return the value of huiyuanxinxi.huiyuanmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuiyuanmingcheng() {
        return huiyuanmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.huiyuanmingcheng
     *
     * @param huiyuanmingcheng the value for huiyuanxinxi.huiyuanmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuiyuanmingcheng(String huiyuanmingcheng) {
        this.huiyuanmingcheng = huiyuanmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.huiyuanbianhao
     *
     * @return the value of huiyuanxinxi.huiyuanbianhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuiyuanbianhao() {
        return huiyuanbianhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.huiyuanbianhao
     *
     * @param huiyuanbianhao the value for huiyuanxinxi.huiyuanbianhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuiyuanbianhao(String huiyuanbianhao) {
        this.huiyuanbianhao = huiyuanbianhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.lianxidianhua
     *
     * @return the value of huiyuanxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLianxidianhua() {
        return lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.lianxidianhua
     *
     * @param lianxidianhua the value for huiyuanxinxi.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLianxidianhua(String lianxidianhua) {
        this.lianxidianhua = lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.fuJian
     *
     * @return the value of huiyuanxinxi.fuJian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getFujian() {
        return fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.fuJian
     *
     * @param fujian the value for huiyuanxinxi.fuJian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setFujian(String fujian) {
        this.fujian = fujian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.operatorId
     *
     * @return the value of huiyuanxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.operatorId
     *
     * @param operatorid the value for huiyuanxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.itime
     *
     * @return the value of huiyuanxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.itime
     *
     * @param itime the value for huiyuanxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.detail
     *
     * @return the value of huiyuanxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.detail
     *
     * @param detail the value for huiyuanxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.deleteFlag
     *
     * @return the value of huiyuanxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.deleteFlag
     *
     * @param deleteflag the value for huiyuanxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanxinxi.zhuangtai
     *
     * @return the value of huiyuanxinxi.zhuangtai
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanxinxi.zhuangtai
     *
     * @param zhuangtai the value for huiyuanxinxi.zhuangtai
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai;
    }
}