package bean;

public class huiyuanjifenBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.huiyuanmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huiyuanmingcheng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huiyuanjifen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column huiyuanjifen.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.id
     *
     * @return the value of huiyuanjifen.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.id
     *
     * @param id the value for huiyuanjifen.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.huiyuanmingcheng
     *
     * @return the value of huiyuanjifen.huiyuanmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuiyuanmingcheng() {
        return huiyuanmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.huiyuanmingcheng
     *
     * @param huiyuanmingcheng the value for huiyuanjifen.huiyuanmingcheng
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuiyuanmingcheng(String huiyuanmingcheng) {
        this.huiyuanmingcheng = huiyuanmingcheng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.huiyuanjifen
     *
     * @return the value of huiyuanjifen.huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuiyuanjifen() {
        return huiyuanjifen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.huiyuanjifen
     *
     * @param huiyuanjifen the value for huiyuanjifen.huiyuanjifen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuiyuanjifen(String huiyuanjifen) {
        this.huiyuanjifen = huiyuanjifen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.operatorId
     *
     * @return the value of huiyuanjifen.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.operatorId
     *
     * @param operatorid the value for huiyuanjifen.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.itime
     *
     * @return the value of huiyuanjifen.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.itime
     *
     * @param itime the value for huiyuanjifen.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.detail
     *
     * @return the value of huiyuanjifen.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.detail
     *
     * @param detail the value for huiyuanjifen.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column huiyuanjifen.deleteFlag
     *
     * @return the value of huiyuanjifen.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column huiyuanjifen.deleteFlag
     *
     * @param deleteflag the value for huiyuanjifen.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}