package bean;

public class jiageshezhiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huohao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.xiaoshoujiage
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String xiaoshoujiage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.shezhiriqi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String shezhiriqi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column jiageshezhi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.id
     *
     * @return the value of jiageshezhi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.id
     *
     * @param id the value for jiageshezhi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.huohao
     *
     * @return the value of jiageshezhi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuohao() {
        return huohao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.huohao
     *
     * @param huohao the value for jiageshezhi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuohao(String huohao) {
        this.huohao = huohao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.xiaoshoujiage
     *
     * @return the value of jiageshezhi.xiaoshoujiage
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getXiaoshoujiage() {
        return xiaoshoujiage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.xiaoshoujiage
     *
     * @param xiaoshoujiage the value for jiageshezhi.xiaoshoujiage
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setXiaoshoujiage(String xiaoshoujiage) {
        this.xiaoshoujiage = xiaoshoujiage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.shezhiriqi
     *
     * @return the value of jiageshezhi.shezhiriqi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getShezhiriqi() {
        return shezhiriqi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.shezhiriqi
     *
     * @param shezhiriqi the value for jiageshezhi.shezhiriqi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setShezhiriqi(String shezhiriqi) {
        this.shezhiriqi = shezhiriqi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.operatorId
     *
     * @return the value of jiageshezhi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.operatorId
     *
     * @param operatorid the value for jiageshezhi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.itime
     *
     * @return the value of jiageshezhi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.itime
     *
     * @param itime the value for jiageshezhi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.detail
     *
     * @return the value of jiageshezhi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.detail
     *
     * @param detail the value for jiageshezhi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column jiageshezhi.deleteFlag
     *
     * @return the value of jiageshezhi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column jiageshezhi.deleteFlag
     *
     * @param deleteflag the value for jiageshezhi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}