package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class neibuyuangongguanliBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public neibuyuangongguanliBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected neibuyuangongguanliBeanExample(neibuyuangongguanliBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table neibuyuangongguanli
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andYuangongxingmingIsNull() {
            addCriterion("yuangongxingming is null");
            return this;
        }

        public Criteria andYuangongxingmingIsNotNull() {
            addCriterion("yuangongxingming is not null");
            return this;
        }

        public Criteria andYuangongxingmingEqualTo(String value) {
            addCriterion("yuangongxingming =", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingNotEqualTo(String value) {
            addCriterion("yuangongxingming <>", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingGreaterThan(String value) {
            addCriterion("yuangongxingming >", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingGreaterThanOrEqualTo(String value) {
            addCriterion("yuangongxingming >=", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingLessThan(String value) {
            addCriterion("yuangongxingming <", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingLessThanOrEqualTo(String value) {
            addCriterion("yuangongxingming <=", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingLike(String value) {
            addCriterion("yuangongxingming like", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingNotLike(String value) {
            addCriterion("yuangongxingming not like", value, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingIn(List<String> values) {
            addCriterion("yuangongxingming in", values, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingNotIn(List<String> values) {
            addCriterion("yuangongxingming not in", values, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingBetween(String value1, String value2) {
            addCriterion("yuangongxingming between", value1, value2, "yuangongxingming");
            return this;
        }

        public Criteria andYuangongxingmingNotBetween(String value1, String value2) {
            addCriterion("yuangongxingming not between", value1, value2, "yuangongxingming");
            return this;
        }

        public Criteria andYuangonggonghaoIsNull() {
            addCriterion("yuangonggonghao is null");
            return this;
        }

        public Criteria andYuangonggonghaoIsNotNull() {
            addCriterion("yuangonggonghao is not null");
            return this;
        }

        public Criteria andYuangonggonghaoEqualTo(String value) {
            addCriterion("yuangonggonghao =", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoNotEqualTo(String value) {
            addCriterion("yuangonggonghao <>", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoGreaterThan(String value) {
            addCriterion("yuangonggonghao >", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoGreaterThanOrEqualTo(String value) {
            addCriterion("yuangonggonghao >=", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoLessThan(String value) {
            addCriterion("yuangonggonghao <", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoLessThanOrEqualTo(String value) {
            addCriterion("yuangonggonghao <=", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoLike(String value) {
            addCriterion("yuangonggonghao like", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoNotLike(String value) {
            addCriterion("yuangonggonghao not like", value, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoIn(List<String> values) {
            addCriterion("yuangonggonghao in", values, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoNotIn(List<String> values) {
            addCriterion("yuangonggonghao not in", values, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoBetween(String value1, String value2) {
            addCriterion("yuangonggonghao between", value1, value2, "yuangonggonghao");
            return this;
        }

        public Criteria andYuangonggonghaoNotBetween(String value1, String value2) {
            addCriterion("yuangonggonghao not between", value1, value2, "yuangonggonghao");
            return this;
        }

        public Criteria andRuzhishijianIsNull() {
            addCriterion("ruzhishijian is null");
            return this;
        }

        public Criteria andRuzhishijianIsNotNull() {
            addCriterion("ruzhishijian is not null");
            return this;
        }

        public Criteria andRuzhishijianEqualTo(String value) {
            addCriterion("ruzhishijian =", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianNotEqualTo(String value) {
            addCriterion("ruzhishijian <>", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianGreaterThan(String value) {
            addCriterion("ruzhishijian >", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianGreaterThanOrEqualTo(String value) {
            addCriterion("ruzhishijian >=", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianLessThan(String value) {
            addCriterion("ruzhishijian <", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianLessThanOrEqualTo(String value) {
            addCriterion("ruzhishijian <=", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianLike(String value) {
            addCriterion("ruzhishijian like", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianNotLike(String value) {
            addCriterion("ruzhishijian not like", value, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianIn(List<String> values) {
            addCriterion("ruzhishijian in", values, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianNotIn(List<String> values) {
            addCriterion("ruzhishijian not in", values, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianBetween(String value1, String value2) {
            addCriterion("ruzhishijian between", value1, value2, "ruzhishijian");
            return this;
        }

        public Criteria andRuzhishijianNotBetween(String value1, String value2) {
            addCriterion("ruzhishijian not between", value1, value2, "ruzhishijian");
            return this;
        }

        public Criteria andJiatingzhuzhiIsNull() {
            addCriterion("jiatingzhuzhi is null");
            return this;
        }

        public Criteria andJiatingzhuzhiIsNotNull() {
            addCriterion("jiatingzhuzhi is not null");
            return this;
        }

        public Criteria andJiatingzhuzhiEqualTo(String value) {
            addCriterion("jiatingzhuzhi =", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiNotEqualTo(String value) {
            addCriterion("jiatingzhuzhi <>", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiGreaterThan(String value) {
            addCriterion("jiatingzhuzhi >", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiGreaterThanOrEqualTo(String value) {
            addCriterion("jiatingzhuzhi >=", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiLessThan(String value) {
            addCriterion("jiatingzhuzhi <", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiLessThanOrEqualTo(String value) {
            addCriterion("jiatingzhuzhi <=", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiLike(String value) {
            addCriterion("jiatingzhuzhi like", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiNotLike(String value) {
            addCriterion("jiatingzhuzhi not like", value, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiIn(List<String> values) {
            addCriterion("jiatingzhuzhi in", values, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiNotIn(List<String> values) {
            addCriterion("jiatingzhuzhi not in", values, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiBetween(String value1, String value2) {
            addCriterion("jiatingzhuzhi between", value1, value2, "jiatingzhuzhi");
            return this;
        }

        public Criteria andJiatingzhuzhiNotBetween(String value1, String value2) {
            addCriterion("jiatingzhuzhi not between", value1, value2, "jiatingzhuzhi");
            return this;
        }

        public Criteria andLianxidianhuaIsNull() {
            addCriterion("lianxidianhua is null");
            return this;
        }

        public Criteria andLianxidianhuaIsNotNull() {
            addCriterion("lianxidianhua is not null");
            return this;
        }

        public Criteria andLianxidianhuaEqualTo(String value) {
            addCriterion("lianxidianhua =", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaNotEqualTo(String value) {
            addCriterion("lianxidianhua <>", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaGreaterThan(String value) {
            addCriterion("lianxidianhua >", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaGreaterThanOrEqualTo(String value) {
            addCriterion("lianxidianhua >=", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaLessThan(String value) {
            addCriterion("lianxidianhua <", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaLessThanOrEqualTo(String value) {
            addCriterion("lianxidianhua <=", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaLike(String value) {
            addCriterion("lianxidianhua like", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaNotLike(String value) {
            addCriterion("lianxidianhua not like", value, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaIn(List<String> values) {
            addCriterion("lianxidianhua in", values, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaNotIn(List<String> values) {
            addCriterion("lianxidianhua not in", values, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaBetween(String value1, String value2) {
            addCriterion("lianxidianhua between", value1, value2, "lianxidianhua");
            return this;
        }

        public Criteria andLianxidianhuaNotBetween(String value1, String value2) {
            addCriterion("lianxidianhua not between", value1, value2, "lianxidianhua");
            return this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorId is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorId is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("operatorId =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("operatorId <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("operatorId >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("operatorId >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("operatorId <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("operatorId <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("operatorId like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("operatorId not like", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("operatorId in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("operatorId not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("operatorId between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("operatorId not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andItimeIsNull() {
            addCriterion("itime is null");
            return this;
        }

        public Criteria andItimeIsNotNull() {
            addCriterion("itime is not null");
            return this;
        }

        public Criteria andItimeEqualTo(String value) {
            addCriterion("itime =", value, "itime");
            return this;
        }

        public Criteria andItimeNotEqualTo(String value) {
            addCriterion("itime <>", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThan(String value) {
            addCriterion("itime >", value, "itime");
            return this;
        }

        public Criteria andItimeGreaterThanOrEqualTo(String value) {
            addCriterion("itime >=", value, "itime");
            return this;
        }

        public Criteria andItimeLessThan(String value) {
            addCriterion("itime <", value, "itime");
            return this;
        }

        public Criteria andItimeLessThanOrEqualTo(String value) {
            addCriterion("itime <=", value, "itime");
            return this;
        }

        public Criteria andItimeLike(String value) {
            addCriterion("itime like", value, "itime");
            return this;
        }

        public Criteria andItimeNotLike(String value) {
            addCriterion("itime not like", value, "itime");
            return this;
        }

        public Criteria andItimeIn(List<String> values) {
            addCriterion("itime in", values, "itime");
            return this;
        }

        public Criteria andItimeNotIn(List<String> values) {
            addCriterion("itime not in", values, "itime");
            return this;
        }

        public Criteria andItimeBetween(String value1, String value2) {
            addCriterion("itime between", value1, value2, "itime");
            return this;
        }

        public Criteria andItimeNotBetween(String value1, String value2) {
            addCriterion("itime not between", value1, value2, "itime");
            return this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteFlag is null");
            return this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteFlag is not null");
            return this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("deleteFlag =", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("deleteFlag <>", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("deleteFlag >", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag >=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("deleteFlag <", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("deleteFlag <=", value, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("deleteFlag in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("deleteFlag not in", values, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag between", value1, value2, "deleteflag");
            return this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteFlag not between", value1, value2, "deleteflag");
            return this;
        }
    }
}