package bean;

public class neibuyuangongguanliBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.yuangongxingming
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String yuangongxingming;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.yuangonggonghao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String yuangonggonghao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.ruzhishijian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String ruzhishijian;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.jiatingzhuzhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String jiatingzhuzhi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String lianxidianhua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column neibuyuangongguanli.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.id
     *
     * @return the value of neibuyuangongguanli.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.id
     *
     * @param id the value for neibuyuangongguanli.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.yuangongxingming
     *
     * @return the value of neibuyuangongguanli.yuangongxingming
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getYuangongxingming() {
        return yuangongxingming;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.yuangongxingming
     *
     * @param yuangongxingming the value for neibuyuangongguanli.yuangongxingming
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setYuangongxingming(String yuangongxingming) {
        this.yuangongxingming = yuangongxingming;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.yuangonggonghao
     *
     * @return the value of neibuyuangongguanli.yuangonggonghao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getYuangonggonghao() {
        return yuangonggonghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.yuangonggonghao
     *
     * @param yuangonggonghao the value for neibuyuangongguanli.yuangonggonghao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setYuangonggonghao(String yuangonggonghao) {
        this.yuangonggonghao = yuangonggonghao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.ruzhishijian
     *
     * @return the value of neibuyuangongguanli.ruzhishijian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getRuzhishijian() {
        return ruzhishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.ruzhishijian
     *
     * @param ruzhishijian the value for neibuyuangongguanli.ruzhishijian
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setRuzhishijian(String ruzhishijian) {
        this.ruzhishijian = ruzhishijian;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.jiatingzhuzhi
     *
     * @return the value of neibuyuangongguanli.jiatingzhuzhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getJiatingzhuzhi() {
        return jiatingzhuzhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.jiatingzhuzhi
     *
     * @param jiatingzhuzhi the value for neibuyuangongguanli.jiatingzhuzhi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setJiatingzhuzhi(String jiatingzhuzhi) {
        this.jiatingzhuzhi = jiatingzhuzhi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.lianxidianhua
     *
     * @return the value of neibuyuangongguanli.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLianxidianhua() {
        return lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.lianxidianhua
     *
     * @param lianxidianhua the value for neibuyuangongguanli.lianxidianhua
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLianxidianhua(String lianxidianhua) {
        this.lianxidianhua = lianxidianhua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.operatorId
     *
     * @return the value of neibuyuangongguanli.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.operatorId
     *
     * @param operatorid the value for neibuyuangongguanli.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.itime
     *
     * @return the value of neibuyuangongguanli.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.itime
     *
     * @param itime the value for neibuyuangongguanli.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.detail
     *
     * @return the value of neibuyuangongguanli.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.detail
     *
     * @param detail the value for neibuyuangongguanli.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column neibuyuangongguanli.deleteFlag
     *
     * @return the value of neibuyuangongguanli.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column neibuyuangongguanli.deleteFlag
     *
     * @param deleteflag the value for neibuyuangongguanli.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}