package bean;

import java.util.Date;

public class organize_infoBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.Id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.orgName
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String orgname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.fID
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer fid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.authorizeNum
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer authorizenum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.startTime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String starttime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.endTime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Date endtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.orgManager
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer orgmanager;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column organize_info.fName
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String fname;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.Id
     *
     * @return the value of organize_info.Id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.Id
     *
     * @param id the value for organize_info.Id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.orgName
     *
     * @return the value of organize_info.orgName
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.orgName
     *
     * @param orgname the value for organize_info.orgName
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.fID
     *
     * @return the value of organize_info.fID
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.fID
     *
     * @param fid the value for organize_info.fID
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.authorizeNum
     *
     * @return the value of organize_info.authorizeNum
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getAuthorizenum() {
        return authorizenum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.authorizeNum
     *
     * @param authorizenum the value for organize_info.authorizeNum
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setAuthorizenum(Integer authorizenum) {
        this.authorizenum = authorizenum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.startTime
     *
     * @return the value of organize_info.startTime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.startTime
     *
     * @param starttime the value for organize_info.startTime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.endTime
     *
     * @return the value of organize_info.endTime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.endTime
     *
     * @param endtime the value for organize_info.endTime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.orgManager
     *
     * @return the value of organize_info.orgManager
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getOrgmanager() {
        return orgmanager;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.orgManager
     *
     * @param orgmanager the value for organize_info.orgManager
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOrgmanager(Integer orgmanager) {
        this.orgmanager = orgmanager;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.detail
     *
     * @return the value of organize_info.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.detail
     *
     * @param detail the value for organize_info.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.deleteFlag
     *
     * @return the value of organize_info.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.deleteFlag
     *
     * @param deleteflag the value for organize_info.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column organize_info.fName
     *
     * @return the value of organize_info.fName
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column organize_info.fName
     *
     * @param fname the value for organize_info.fName
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setFname(String fname) {
        this.fname = fname;
    }
}