package bean;

public class shangpinleixingBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shangpinleixing.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shangpinleixing.shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String shangpinleixing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shangpinleixing.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shangpinleixing.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shangpinleixing.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column shangpinleixing.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shangpinleixing.id
     *
     * @return the value of shangpinleixing.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shangpinleixing.id
     *
     * @param id the value for shangpinleixing.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shangpinleixing.shangpinleixing
     *
     * @return the value of shangpinleixing.shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getShangpinleixing() {
        return shangpinleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shangpinleixing.shangpinleixing
     *
     * @param shangpinleixing the value for shangpinleixing.shangpinleixing
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setShangpinleixing(String shangpinleixing) {
        this.shangpinleixing = shangpinleixing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shangpinleixing.operatorId
     *
     * @return the value of shangpinleixing.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shangpinleixing.operatorId
     *
     * @param operatorid the value for shangpinleixing.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shangpinleixing.itime
     *
     * @return the value of shangpinleixing.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shangpinleixing.itime
     *
     * @param itime the value for shangpinleixing.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shangpinleixing.detail
     *
     * @return the value of shangpinleixing.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shangpinleixing.detail
     *
     * @param detail the value for shangpinleixing.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column shangpinleixing.deleteFlag
     *
     * @return the value of shangpinleixing.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column shangpinleixing.deleteFlag
     *
     * @param deleteflag the value for shangpinleixing.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}