package bean;

public class wenzhangguanliBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.wenzhangbiaoti
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String wenzhangbiaoti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.fubiaoti
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String fubiaoti;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.zhengwen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String zhengwen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.luokuan
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String luokuan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.suoshulanmu
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String suoshulanmu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column wenzhangguanli.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.id
     *
     * @return the value of wenzhangguanli.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.id
     *
     * @param id the value for wenzhangguanli.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.wenzhangbiaoti
     *
     * @return the value of wenzhangguanli.wenzhangbiaoti
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getWenzhangbiaoti() {
        return wenzhangbiaoti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.wenzhangbiaoti
     *
     * @param wenzhangbiaoti the value for wenzhangguanli.wenzhangbiaoti
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setWenzhangbiaoti(String wenzhangbiaoti) {
        this.wenzhangbiaoti = wenzhangbiaoti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.fubiaoti
     *
     * @return the value of wenzhangguanli.fubiaoti
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getFubiaoti() {
        return fubiaoti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.fubiaoti
     *
     * @param fubiaoti the value for wenzhangguanli.fubiaoti
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setFubiaoti(String fubiaoti) {
        this.fubiaoti = fubiaoti;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.zhengwen
     *
     * @return the value of wenzhangguanli.zhengwen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getZhengwen() {
        return zhengwen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.zhengwen
     *
     * @param zhengwen the value for wenzhangguanli.zhengwen
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setZhengwen(String zhengwen) {
        this.zhengwen = zhengwen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.luokuan
     *
     * @return the value of wenzhangguanli.luokuan
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getLuokuan() {
        return luokuan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.luokuan
     *
     * @param luokuan the value for wenzhangguanli.luokuan
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setLuokuan(String luokuan) {
        this.luokuan = luokuan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.suoshulanmu
     *
     * @return the value of wenzhangguanli.suoshulanmu
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getSuoshulanmu() {
        return suoshulanmu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.suoshulanmu
     *
     * @param suoshulanmu the value for wenzhangguanli.suoshulanmu
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setSuoshulanmu(String suoshulanmu) {
        this.suoshulanmu = suoshulanmu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.operatorId
     *
     * @return the value of wenzhangguanli.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.operatorId
     *
     * @param operatorid the value for wenzhangguanli.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.itime
     *
     * @return the value of wenzhangguanli.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.itime
     *
     * @param itime the value for wenzhangguanli.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.detail
     *
     * @return the value of wenzhangguanli.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.detail
     *
     * @param detail the value for wenzhangguanli.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column wenzhangguanli.deleteFlag
     *
     * @return the value of wenzhangguanli.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column wenzhangguanli.deleteFlag
     *
     * @param deleteflag the value for wenzhangguanli.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}