package bean;

public class xiaoshouxinxi_mingxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.xiaoshoudanhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String xiaoshoudanhao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huohao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.shuliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String shuliang;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.danjia
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String danjia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.xiaoji
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String xiaoji;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi_mingxi.beizhu
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String beizhu;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.id
     *
     * @return the value of xiaoshouxinxi_mingxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.id
     *
     * @param id the value for xiaoshouxinxi_mingxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.xiaoshoudanhao
     *
     * @return the value of xiaoshouxinxi_mingxi.xiaoshoudanhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getXiaoshoudanhao() {
        return xiaoshoudanhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.xiaoshoudanhao
     *
     * @param xiaoshoudanhao the value for xiaoshouxinxi_mingxi.xiaoshoudanhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setXiaoshoudanhao(String xiaoshoudanhao) {
        this.xiaoshoudanhao = xiaoshoudanhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.huohao
     *
     * @return the value of xiaoshouxinxi_mingxi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuohao() {
        return huohao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.huohao
     *
     * @param huohao the value for xiaoshouxinxi_mingxi.huohao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuohao(String huohao) {
        this.huohao = huohao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.shuliang
     *
     * @return the value of xiaoshouxinxi_mingxi.shuliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.shuliang
     *
     * @param shuliang the value for xiaoshouxinxi_mingxi.shuliang
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setShuliang(String shuliang) {
        this.shuliang = shuliang;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.danjia
     *
     * @return the value of xiaoshouxinxi_mingxi.danjia
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDanjia() {
        return danjia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.danjia
     *
     * @param danjia the value for xiaoshouxinxi_mingxi.danjia
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDanjia(String danjia) {
        this.danjia = danjia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.xiaoji
     *
     * @return the value of xiaoshouxinxi_mingxi.xiaoji
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getXiaoji() {
        return xiaoji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.xiaoji
     *
     * @param xiaoji the value for xiaoshouxinxi_mingxi.xiaoji
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setXiaoji(String xiaoji) {
        this.xiaoji = xiaoji;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi_mingxi.beizhu
     *
     * @return the value of xiaoshouxinxi_mingxi.beizhu
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi_mingxi.beizhu
     *
     * @param beizhu the value for xiaoshouxinxi_mingxi.beizhu
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }
}