package bean;

public class xiaoshouxinxiBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.xiaoshoudanhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String xiaoshoudanhao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.jingshouren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String jingshouren;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.xiaofeijine
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String xiaofeijine;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.huiyuanbianhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String huiyuanbianhao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String operatorid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String itime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private String detail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column xiaoshouxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    private Integer deleteflag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.id
     *
     * @return the value of xiaoshouxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.id
     *
     * @param id the value for xiaoshouxinxi.id
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.xiaoshoudanhao
     *
     * @return the value of xiaoshouxinxi.xiaoshoudanhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getXiaoshoudanhao() {
        return xiaoshoudanhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.xiaoshoudanhao
     *
     * @param xiaoshoudanhao the value for xiaoshouxinxi.xiaoshoudanhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setXiaoshoudanhao(String xiaoshoudanhao) {
        this.xiaoshoudanhao = xiaoshoudanhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.jingshouren
     *
     * @return the value of xiaoshouxinxi.jingshouren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getJingshouren() {
        return jingshouren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.jingshouren
     *
     * @param jingshouren the value for xiaoshouxinxi.jingshouren
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setJingshouren(String jingshouren) {
        this.jingshouren = jingshouren;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.xiaofeijine
     *
     * @return the value of xiaoshouxinxi.xiaofeijine
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getXiaofeijine() {
        return xiaofeijine;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.xiaofeijine
     *
     * @param xiaofeijine the value for xiaoshouxinxi.xiaofeijine
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setXiaofeijine(String xiaofeijine) {
        this.xiaofeijine = xiaofeijine;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.huiyuanbianhao
     *
     * @return the value of xiaoshouxinxi.huiyuanbianhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getHuiyuanbianhao() {
        return huiyuanbianhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.huiyuanbianhao
     *
     * @param huiyuanbianhao the value for xiaoshouxinxi.huiyuanbianhao
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setHuiyuanbianhao(String huiyuanbianhao) {
        this.huiyuanbianhao = huiyuanbianhao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.operatorId
     *
     * @return the value of xiaoshouxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.operatorId
     *
     * @param operatorid the value for xiaoshouxinxi.operatorId
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.itime
     *
     * @return the value of xiaoshouxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getItime() {
        return itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.itime
     *
     * @param itime the value for xiaoshouxinxi.itime
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setItime(String itime) {
        this.itime = itime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.detail
     *
     * @return the value of xiaoshouxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.detail
     *
     * @param detail the value for xiaoshouxinxi.detail
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column xiaoshouxinxi.deleteFlag
     *
     * @return the value of xiaoshouxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column xiaoshouxinxi.deleteFlag
     *
     * @param deleteflag the value for xiaoshouxinxi.deleteFlag
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}