package bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class xiaoshouxinxi_mingxiBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public xiaoshouxinxi_mingxiBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected xiaoshouxinxi_mingxiBeanExample(xiaoshouxinxi_mingxiBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table xiaoshouxinxi_mingxi
     *
     * @ibatorgenerated Wed Apr 04 09:32:08 CST 2018
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andXiaoshoudanhaoIsNull() {
            addCriterion("xiaoshoudanhao is null");
            return this;
        }

        public Criteria andXiaoshoudanhaoIsNotNull() {
            addCriterion("xiaoshoudanhao is not null");
            return this;
        }

        public Criteria andXiaoshoudanhaoEqualTo(String value) {
            addCriterion("xiaoshoudanhao =", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoNotEqualTo(String value) {
            addCriterion("xiaoshoudanhao <>", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoGreaterThan(String value) {
            addCriterion("xiaoshoudanhao >", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoGreaterThanOrEqualTo(String value) {
            addCriterion("xiaoshoudanhao >=", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoLessThan(String value) {
            addCriterion("xiaoshoudanhao <", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoLessThanOrEqualTo(String value) {
            addCriterion("xiaoshoudanhao <=", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoLike(String value) {
            addCriterion("xiaoshoudanhao like", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoNotLike(String value) {
            addCriterion("xiaoshoudanhao not like", value, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoIn(List<String> values) {
            addCriterion("xiaoshoudanhao in", values, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoNotIn(List<String> values) {
            addCriterion("xiaoshoudanhao not in", values, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoBetween(String value1, String value2) {
            addCriterion("xiaoshoudanhao between", value1, value2, "xiaoshoudanhao");
            return this;
        }

        public Criteria andXiaoshoudanhaoNotBetween(String value1, String value2) {
            addCriterion("xiaoshoudanhao not between", value1, value2, "xiaoshoudanhao");
            return this;
        }

        public Criteria andHuohaoIsNull() {
            addCriterion("huohao is null");
            return this;
        }

        public Criteria andHuohaoIsNotNull() {
            addCriterion("huohao is not null");
            return this;
        }

        public Criteria andHuohaoEqualTo(String value) {
            addCriterion("huohao =", value, "huohao");
            return this;
        }

        public Criteria andHuohaoNotEqualTo(String value) {
            addCriterion("huohao <>", value, "huohao");
            return this;
        }

        public Criteria andHuohaoGreaterThan(String value) {
            addCriterion("huohao >", value, "huohao");
            return this;
        }

        public Criteria andHuohaoGreaterThanOrEqualTo(String value) {
            addCriterion("huohao >=", value, "huohao");
            return this;
        }

        public Criteria andHuohaoLessThan(String value) {
            addCriterion("huohao <", value, "huohao");
            return this;
        }

        public Criteria andHuohaoLessThanOrEqualTo(String value) {
            addCriterion("huohao <=", value, "huohao");
            return this;
        }

        public Criteria andHuohaoLike(String value) {
            addCriterion("huohao like", value, "huohao");
            return this;
        }

        public Criteria andHuohaoNotLike(String value) {
            addCriterion("huohao not like", value, "huohao");
            return this;
        }

        public Criteria andHuohaoIn(List<String> values) {
            addCriterion("huohao in", values, "huohao");
            return this;
        }

        public Criteria andHuohaoNotIn(List<String> values) {
            addCriterion("huohao not in", values, "huohao");
            return this;
        }

        public Criteria andHuohaoBetween(String value1, String value2) {
            addCriterion("huohao between", value1, value2, "huohao");
            return this;
        }

        public Criteria andHuohaoNotBetween(String value1, String value2) {
            addCriterion("huohao not between", value1, value2, "huohao");
            return this;
        }

        public Criteria andShuliangIsNull() {
            addCriterion("shuliang is null");
            return this;
        }

        public Criteria andShuliangIsNotNull() {
            addCriterion("shuliang is not null");
            return this;
        }

        public Criteria andShuliangEqualTo(String value) {
            addCriterion("shuliang =", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotEqualTo(String value) {
            addCriterion("shuliang <>", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThan(String value) {
            addCriterion("shuliang >", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThanOrEqualTo(String value) {
            addCriterion("shuliang >=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThan(String value) {
            addCriterion("shuliang <", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThanOrEqualTo(String value) {
            addCriterion("shuliang <=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLike(String value) {
            addCriterion("shuliang like", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotLike(String value) {
            addCriterion("shuliang not like", value, "shuliang");
            return this;
        }

        public Criteria andShuliangIn(List<String> values) {
            addCriterion("shuliang in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangNotIn(List<String> values) {
            addCriterion("shuliang not in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangBetween(String value1, String value2) {
            addCriterion("shuliang between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andShuliangNotBetween(String value1, String value2) {
            addCriterion("shuliang not between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andDanjiaIsNull() {
            addCriterion("danjia is null");
            return this;
        }

        public Criteria andDanjiaIsNotNull() {
            addCriterion("danjia is not null");
            return this;
        }

        public Criteria andDanjiaEqualTo(String value) {
            addCriterion("danjia =", value, "danjia");
            return this;
        }

        public Criteria andDanjiaNotEqualTo(String value) {
            addCriterion("danjia <>", value, "danjia");
            return this;
        }

        public Criteria andDanjiaGreaterThan(String value) {
            addCriterion("danjia >", value, "danjia");
            return this;
        }

        public Criteria andDanjiaGreaterThanOrEqualTo(String value) {
            addCriterion("danjia >=", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLessThan(String value) {
            addCriterion("danjia <", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLessThanOrEqualTo(String value) {
            addCriterion("danjia <=", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLike(String value) {
            addCriterion("danjia like", value, "danjia");
            return this;
        }

        public Criteria andDanjiaNotLike(String value) {
            addCriterion("danjia not like", value, "danjia");
            return this;
        }

        public Criteria andDanjiaIn(List<String> values) {
            addCriterion("danjia in", values, "danjia");
            return this;
        }

        public Criteria andDanjiaNotIn(List<String> values) {
            addCriterion("danjia not in", values, "danjia");
            return this;
        }

        public Criteria andDanjiaBetween(String value1, String value2) {
            addCriterion("danjia between", value1, value2, "danjia");
            return this;
        }

        public Criteria andDanjiaNotBetween(String value1, String value2) {
            addCriterion("danjia not between", value1, value2, "danjia");
            return this;
        }

        public Criteria andXiaojiIsNull() {
            addCriterion("xiaoji is null");
            return this;
        }

        public Criteria andXiaojiIsNotNull() {
            addCriterion("xiaoji is not null");
            return this;
        }

        public Criteria andXiaojiEqualTo(String value) {
            addCriterion("xiaoji =", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiNotEqualTo(String value) {
            addCriterion("xiaoji <>", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiGreaterThan(String value) {
            addCriterion("xiaoji >", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiGreaterThanOrEqualTo(String value) {
            addCriterion("xiaoji >=", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiLessThan(String value) {
            addCriterion("xiaoji <", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiLessThanOrEqualTo(String value) {
            addCriterion("xiaoji <=", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiLike(String value) {
            addCriterion("xiaoji like", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiNotLike(String value) {
            addCriterion("xiaoji not like", value, "xiaoji");
            return this;
        }

        public Criteria andXiaojiIn(List<String> values) {
            addCriterion("xiaoji in", values, "xiaoji");
            return this;
        }

        public Criteria andXiaojiNotIn(List<String> values) {
            addCriterion("xiaoji not in", values, "xiaoji");
            return this;
        }

        public Criteria andXiaojiBetween(String value1, String value2) {
            addCriterion("xiaoji between", value1, value2, "xiaoji");
            return this;
        }

        public Criteria andXiaojiNotBetween(String value1, String value2) {
            addCriterion("xiaoji not between", value1, value2, "xiaoji");
            return this;
        }

        public Criteria andBeizhuIsNull() {
            addCriterion("beizhu is null");
            return this;
        }

        public Criteria andBeizhuIsNotNull() {
            addCriterion("beizhu is not null");
            return this;
        }

        public Criteria andBeizhuEqualTo(String value) {
            addCriterion("beizhu =", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotEqualTo(String value) {
            addCriterion("beizhu <>", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuGreaterThan(String value) {
            addCriterion("beizhu >", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
            addCriterion("beizhu >=", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLessThan(String value) {
            addCriterion("beizhu <", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLessThanOrEqualTo(String value) {
            addCriterion("beizhu <=", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLike(String value) {
            addCriterion("beizhu like", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotLike(String value) {
            addCriterion("beizhu not like", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuIn(List<String> values) {
            addCriterion("beizhu in", values, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotIn(List<String> values) {
            addCriterion("beizhu not in", values, "beizhu");
            return this;
        }

        public Criteria andBeizhuBetween(String value1, String value2) {
            addCriterion("beizhu between", value1, value2, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotBetween(String value1, String value2) {
            addCriterion("beizhu not between", value1, value2, "beizhu");
            return this;
        }
    }
}